- package.json
- yarn.lock
Now the `dist` folder (which can be used, for example, through `unpkg`) will contain both the "original" output from Tailwind plus a minified copy of the file, as well as a source map.
For reference, `unpkg` can be used like so:
https://unpkg.com/@movable/tailwind-config@0.2.1/dist/fluid-tailwind.css
Note: I added `--no-restructure` to try to avoid cases where the compressor might try to be clever and re-arrange declarations. Since Tailwind's usage depends on the relative ordering of base/component/utility classes, we went to make sure that that is preserved as much as possible.
Really, we just want the minifier to deflate the whitespace and strip out comments that would otherwise be downloaded on every request.
The savings we get with `csso` is pretty considerable
```
Source: …
```
> feat: provide minified pre-built file through `csso`

- config/typography.js
- plugins/base.js
- stories/Font/weight.stories.js
Following discussion today, it was decided that we only need to define
a single weight (besides `normal`), `bold`, which would use the `600`
weight that is recommended by the brand team (instead of the default
`700`).
This allows developers to ignore the fact that we technically never want
to use "bold", and instead always want "semibold".
We also style the semantic `b` and `strong` elements with the correct
weight.
> fix: drop `fontWeight` besides `bold`

- .eslintrc.json
- .github/workflows/commit-lint.yml
- .github/workflows/deploy.yml
- .github/workflows/verify.yml
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- package.json
- yarn.lock
- Add `lint-staged` to verify formatting before committing
- Configure `standard-version` to prettify changelog before publishing
- Add `prettier` to check formatting of non-JS files in CI
> chore: enforce linting before committing

- .github/workflows/verify.yml
- README.md
- package.json
- stories/Components/BodyText/index.stories.js
- stories/Components/CaptionText.stories.js
- stories/Components/HeadingText.stories.js
- stories/Utilities/Font/letter-spacing.stories.js
- stories/Utilities/Font/line-height.stories.js
- stories/Utilities/Font/size.stories.js
- stories/Utilities/Font/weight.stories.js
- stories/_utils/random.js
- yarn.lock
@keser and I talked about adding Percy to the Tailwind config, to give a way to understand how changes impact the project.
Percy already has great Storybook support, through a GitHub Action no less! This should allow us to get a Percy snapshot for every Storybook story.
> chore(ci): add action to run Percy

- config/typography.js
- plugins/base.js
- stories/Utilities/Font/line-height.stories.js
I think that the intended values for `line-height` and the way that it got implemented ended up slightly out-of-sync, due to the difference between a `line-height` value without a unit and using `rem`.
The documentation in Notion lists values without units, but the way that it's described, it seems like what we actually want is to use a `rem` unit for the values.
> Fix line height to match expectations 

- index.js
- tests/no-size-classes.js
The max- and min- height and width plugins from Tailwind actually are not configured based on a scale at all. 
Because of this, it's really unlikely that we would have an opinion on what sizes are made available
to use with them. They should be safe for us to enable even before we have the actual height/width size scale defined.
Related to #22
> feat: enable max/min height/width plugins

- README.md
@keser asked me about whether we could have a static build of Tailwind somewhere, so we can use CodePen (or anything else) as a playground for prototyping things with our Tailwind configuration.
Since we already have that static build, I went and created a CodePen template that includes the links to the Google Fonts and Tailwind build on `unpkg`.
This adds a badge to our README that will create a new CodePen for you with that template. It also updates the `unpkg` URL to use `https`; CodePen warned about the original `http` link.
> Add CodePen template link to README

- index.js
This reverts commit 3ea23d75fbf09f062be03e55129a27a48dba4fc7.
***
Adding `!important` caused a lot of breaking changes in Canvas, and I think is overall too dangerous of a move.
Not including it will just mean that we have to be more diligent about removing "old" styles as we transition to Tailwind.
> Revert "feat: generate classes with `!important`"

- .github/workflows/report-file-size.yml
To avoid the comments from the GitHub Actions bot getting annoying, when the file sizes had no change, it now only actually reports the file sizes if the _base_ `fluid-tailwind.css` file has a different size.
> Only report file size to PR if changed

- .eslintrc.json
- .github/workflows/deploy.yml
- .storybook/preview-head.html
- .storybook/preview.js
- package.json
- stories/Components/BodyText/cookbook.stories.js
- stories/Components/BodyText/index.stories.js
- stories/Components/CaptionText.stories.js
- stories/Components/HeadingText.stories.js
- stories/Guides/color.stories.js
- stories/Guides/palette.stories.js
- stories/Utilities/Color/text.stories.js
- stories/Utilities/Font/letter-spacing.stories.js
- stories/Utilities/Font/line-height.stories.js
- stories/Utilities/Font/size.stories.js
- stories/Utilities/Font/weight.stories.js
- stories/_utils/Callout.js
- stories/_utils/Example.js
- stories/_utils/InlineCode.js
- stories/_utils/callout.js
- yarn.lock
A big part of this PR is hooking up HTM and Preact, so that we can have things like components that we use to share functionality across our documentation pages. I thought about just using the React storybook support, but at least for now decided that that is quite a bit more heavy-handed than what we really need. I may decide to switch to that in the future, but for now Preact and HTM get us a similar experience with much less code.
The motivator to being in a component framework was to allow us to have a component that, given a snippet of code, would both render it _and_ show the code that produces it. This I was able to achieve pretty easily with the Preact libraries that are available. An example of what this looks like is here:
I also went ahead and added a page about our color …
> Docs Site Improvements

- .github/workflows/verify.yml
- package.json
- stories/Utilities/Font/line-height.stories.js
- stories/_utils/Example.js
- yarn.lock
I tried to get this working yesterday, but decided to just land the changes I was making with out it. Today I was able to work out a _very_ hacky solution to the problem I was seeing.
Preact, when rendering some content to a string, strips out all the whitespace. That made all of our code examples render like this:
Everything is on a single line. Not a bit deal for these really simple examples, but it would be nice to allow for multiple lines in cases, like a form or table, where the code example is a lot larger.
I was able to work out how to get the indentation "just right" by rendering the example to a string _with_ whitespace, when injecting that content into the code example outside of the Preact rendering cycle, bypassing its whitespace logic.
With whitespace preserved, it's easier …
> docs: fix indentation in code examples

- .storybook/.babelrc
- stories/Guides/color.stories.js
Took a pass at updating out color palette docs based on what Shopify does for Polaris
https://polaris.shopify.com/design/colors#section-color-palette
Now you can see the hex values for each color, and we actually pull the palette data from the configuration itself. No need to maintain two copies -- if change the color configuration, the documentation will change automatically too!
> Updated color palette docs

- .storybook/preview.js
This change makes a small improvement to the HTML snippet rendered in the Addon panel for each story.
We use a Storybook "decorator" to wrap each story in a little spacing to avoid the elements from butting right up to the edges of the page.
However, the original way this was implemented, the wrapper element ended up in the snippet
By re-ordering the decorators, we can avoid this and remove the wrapper from the snippet
> Remove wrapper from code snippet

- config/typography.js
This change brings our font-size configuration better in-line with the values used in design.
The original implementation used `rem` values calculated based on a scale, which was mathematically correct but hard for designers to use. The designs round to the nearest pixel value.
Now, instead of hoping that the browser also rounds to the same pixel value (since raw `rem` can end up with sub-pixel font sizes that are then rounded when rendered), we just calculate a `rem` value that mathematically matches the `px` value used by design.
This gives us better dev/design consistency _and_ makes implementations easier, as the font sizes are nice round numbers instead of fractions of a pixel.
> fix: ensure font sizes match clean `px` sizes

- plugins/components/buttons.js
- stories/Components/Buttons/CookBook.stories.js
This adds a `.fluid-button-group` class that you can wrap around a set of buttons to place them into a "group".
Buttons in a group have their border radii set such that only the left-most and right-most buttons have rounded corners and there is only a single pixel of border between each of the buttons.
🏠 [ch38600](https://app.clubhouse.io/movableink/story/38600)
> feat: add `fluid-button-group` styles

- .storybook/main.js
- .storybook/preview.js
- package.json
- plugins/components/buttons.js
- stories/Components/Buttons/CookBook.stories.js
- yarn.lock
This change allows the Tailwind `text-xxx` helpers to override the text color for a button.
The styles were written in such a way that the CSS, in a simplified way, looked something like this:
```css
.fluid-button.type:outline {
color: 'black';
}
.text-white {
color: 'white';
}
```
*Note: our buttons are specifically inserted into the CSS payload before the utilities, so we know that this order is the case*
We can imagine that some element wants to override the text color of the `type:outline` button to, for example, allow it to appear OK in a "dark mode" situation. It would provide the markup like this:
```html
<button class="fluid-button type:outline text-white">
Click Me!
</button>
```
However, this doesn't work!
Because the `color` property is set at the conjunction of _two_ classes, …
> Allow overriding button text color

- plugins/components/buttons.js
- stories/Components/Buttons/CookBook.stories.js
While #141 worked for the general case of override the default text color, it _did not_ work for overriding variants (like `hover:`).
Essentially, the selectors used to generate the styles for the different button states were higher specificity than the variant utilities provided by Tailwind. Our selectors are higher specificity because we write some explicit selector logic in them to ensure that, for example, the `hover` styles are not applied when a button is `disabled`.
The solution was to ensure that _only_ the actual `.fluid-button` selector ever sets the `color` property; all other selectors just set a CSS variable that that property reads from.
This has the benefit of simplifying the implementation, as we only have a single `--fluid-button-color` variable now.
An alternative …
> fix: allow Tailwind variants to override button styles

- index.js
- package.json
- stories/Utilities/Shadow.stories.js
- yarn.lock
This adds a few changes to the Tailwind config that will be necessary to build out the Ember `FluidTextInput` component using Tailwind.
> Add `border` variants, `shadow-outline` utilities

- plugins/components/buttons.js
- stories/Components/ButtonGroup.stories.js
Currently, the `fluid-button-group` -- when applied to buttons of `type:plain` -- looks like this:
However, throughout our platform where this pattern is used (not often, but it does happen) we introduce a dividing line between them.
Unfortunately, due to CSS specificity, we can't use the `divide` helper from Tailwind to make it work explicitly.
What would be better, though, is making it "just work" and having a nice dividing line between the buttons automatically, which this PR introduces.
Closes #256
> fix: add border between `type:plain` buttons in group

- .github/workflows/verify.yml
I noticed an issue with how Storybook is rendering in Percy when we make use of the Background addon, introduced in #305.
We're also out-of-date with our Percy action, so I am hoping that this (somehow) will fix that issue. It might not, but it's worth trying.
There's an issue with `npx` (used in the updated Percy action) and Volta (volta-cli/action#48) so we're manually defining the whole command to run,rather than running the default `npx`-based command.
> Update GitHub Action for Percy

- CONTRIBUTING.md
- package.json
After our (@nicksteffens and I's) conversation a few days ago on Slack, I realized that the development environment documentation left a lot to be desired.
Tailwind now (and maybe always, though I'm not sure) supports a `--watch` flag for re-building the output when any input (config or CSS base files) change, which is now documented. It has also been made clear that two terminal windows (or TMUX panes, or _something_) are needed to run both Storybook _and_ the Tailwind build at the same time.
> Update Development Environment Docs

- package.json
- yarn.lock
- This can allow command injection
[🎟️[sc-66417]](https://app.shortcut.com/movableink/story/66417/movable-tailwind-config-security-error-shell-quote)
> fix(security): shell-quote has been flagged <1.7.2

- config/typography.js
[sc-74721]
Normalizes monospace font stack to make it less likely to choose Courier.
> Update monospace font stack

- config/typography.js
- index.js
- plugins/components/mui-typography.js
- stories/Components/Text/MuiText.stories.js
All the incoming changes with default `h1, h2, h3, h4, h5, h6`
> feat: mui typography changes
